// <auto-generated />
namespace E_Ticaret.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bookClassSildimBiseyler : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bookClassSildimBiseyler));
        
        string IMigrationMetadata.Id
        {
            get { return "201703251009551_bookClassSildimBiseyler"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
